### ISSUE TITLE
Update to 1.4.1

### ISSUE THREAD

**Issue by Aph-ra** [vcmi-mods/new-old-heroes#3]
Changed Escaton's specialty image to Armageddon; Added Forge and Forge2k conflict warnings.

[new-old-heroes-v1.4.1-vcmi.zip](https://github.com/user-attachments/files/17413261/new-old-heroes-v1.4.1-vcmi.zip)

**Comment by Aph-ra** [comment]
Update to 1.4.2: Changed Escaton (Forge) to have upgraded level 6 units (same as Forge2k)

[new-old-heroes-v1.4.2-vcmi.zip](https://github.com/user-attachments/files/17421515/new-old-heroes-v1.4.2-vcmi.zip)

**Comment by Aph-ra** [comment]
Hero profile graphics for "screenshots": [screenshots.zip](https://github.com/user-attachments/files/17415966/screenshots.zip)

**Comment by GeorgeK1ng** [comment]
@Aph-ra Let me know, if it's your final version for now. I will create PR with your changes inlcuding Czech translation at once.

**Comment by Aph-ra** [comment]
> @Aph-ra Let me know, if it's your final version for now. I will create PR with your changes inlcuding Czech translation at once.

Sorry for the late reply, but yes, I don't plan on updating this for a little while now - feel free to make the translation!

**Comment by Aph-ra** [comment]
Quick fix for forge and forge2k submods should be pushed asap to avoid issues: (Un32Arma.png has an extra ".png" in the file name)

[mods.zip](https://github.com/user-attachments/files/17468605/mods.zip)
